---
- name: Install packages that allow apt to be used over HTTP
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - fuse-overlayfs

- name: Add Kubernetes repo using key from URL.
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/"
    components: [binary]
    signed_by: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    state: present
    enabled: true

- name: Disable upgrade of packages that require reboot
  tags: always
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - linux-image-amd64
    - libc6
    - dbus
    - systemd
    - udev

- name: Update system
  tags: always
  apt:
    update_cache: yes
    name: "*"
    state: latest
