---
- name: Install packages that allow apt to be used over HTTP
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - fuse-overlayfs

- name: Add Kubernetes apt repository key.
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: '0644'
    force: true

- name: Add Kubernetes apt repository.
  ansible.builtin.apt_repository:
    repo: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present

- name: Update system
  tags: always
  apt:
    update_cache: yes
    name: "*"
    state: latest
